[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"

domain = { path = "../domain/", version = "*" }
derive-new = { workspace = true }
tokio = { workspace = true }
