[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
domain = { path = "../domain/", version = "*" }
protocol = { path = "../protocol/", version = "*" }

strum = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
