[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain/", version = "*" }
protocol = { path = "../protocol/", version = "*" }

tokio = { workspace = true }
uuid = { workspace = true }
